//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TfsProperties.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TfsProperties.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2010 Frank Schwieterman
        ///
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining
        ///a copy of this software and associated documentation files (the
        ///&quot;Software&quot;), to deal in the Software without restriction, including
        ///without limitation the rights to use, copy, modify, merge, publish,
        ///distribute, sublicense, and/or sell copies of the Software, and to
        ///permit persons to whom the Software is furnished to do so, subject to
        ///the following conditions:
        ///
        ///
        ///The above copyright notic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManyConsoleLicense {
            get {
                return ResourceManager.GetString("ManyConsoleLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TfsProperties uses ManyConsole which is licensed under the following terms and conditions:.
        /// </summary>
        internal static string ManyConsoleLicenseIntro {
            get {
                return ResourceManager.GetString("ManyConsoleLicenseIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) &lt;year&gt; &lt;copyright holders&gt;
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        /// of this software and associated documentation files (the &quot;Software&quot;), to deal
        /// in the Software without restriction, including without limitation the rights
        /// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        /// copies of the Software, and to permit persons to whom the Software is
        /// furnished to do so, subject to the following conditions:        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NDeskOptionsLicense {
            get {
                return ResourceManager.GetString("NDeskOptionsLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TfsProperties uses NDesk.Options which is licensed under the following terms and conditions:.
        /// </summary>
        internal static string NDeskOptionsLicenseIntro {
            get {
                return ResourceManager.GetString("NDeskOptionsLicenseIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C) 2011-2013 AIT GmbH &amp; Co. KG
        ///
        ///License Terms
        ///=============
        ///
        ///This software is distributed under:
        ///Microsoft Public License (Ms-PL)
        ///Published October 12, 2006
        ///
        ///This license governs use of the accompanying software. If you use the software, you accept this license. If you do not accept the license, do not use the software.
        ///
        ///1. Definitions
        ///The terms &quot;reproduce,&quot; &quot;reproduction,&quot; &quot;derivative works,&quot; and &quot;distribution&quot; have the same meaning here as under U.S. copyright law.
        ///
        ///A &quot;contribution&quot; is the o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TfsPropertiesLicense {
            get {
                return ResourceManager.GetString("TfsPropertiesLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TfsProperties is licensed under the following terms and conditions:.
        /// </summary>
        internal static string TfsPropertiesLicenseIntro {
            get {
                return ResourceManager.GetString("TfsPropertiesLicenseIntro", resourceCulture);
            }
        }
    }
}
